name: Shorebird Patch (Auto en cada push)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  patch-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Shorebird
        uses: shorebirdtech/setup-shorebird@v1
        with:
          cache: true

      - name: Get Dependencies
        run: |
          chmod +x android/gradlew
          shorebird flutter pub get

      - name: Enviar Parche con Shorebird
        run: |
          shorebird patch android --release-version=latest --allow-asset-diffs --allow-native-diffs
        env:
          SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
